name: Scrape the latest data

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '6,26,46 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  treasurydirect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Scrap US Bonds
        run: curl 'https://www.treasurydirect.gov/TA_WS/securities/auctioned?format=json&type=Bond' | jq > US_Bond.json
      - name: Scrap US Notes
        run: curl 'https://www.treasurydirect.gov/TA_WS/securities/auctioned?format=json&type=Note' | jq > US_Note.json
      - name: Scrap US Bills
        run: curl 'https://www.treasurydirect.gov/TA_WS/securities/auctioned?format=json&type=Bill' | jq > US_Bill.json
      - name: Scrap US FRNs
        run: curl 'https://www.treasurydirect.gov/TA_WS/securities/auctioned?format=json&type=FRN' | jq > US_FRN.json
      - name: Scrap US TIPS's
        run: curl 'https://www.treasurydirect.gov/TA_WS/securities/auctioned?format=json&type=TIPS' | jq > US_TIPS.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
