name: Scrape the latest data

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '6,26,46 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  treasurydirect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Scrap US Bonds
        run: curl 'https://www.treasurydirect.gov/TA_WS/securities/auctioned?format=json&type=Bond' | jq > US_Bond.json
        
